const provinsi = new Map([
  ['1', { kode: 'id-ba', jumlah: 0 }],
  ['2', { kode: 'id-bb', jumlah: 0 }],
  ['3', { kode: 'id-bt', jumlah: 0 }],
  ['4', { kode: 'id-be', jumlah: 0 }],
  ['5', { kode: 'id-yo', jumlah: 0 }],
  ['6', { kode: 'id-jk', jumlah: 0 }],
  ['7', { kode: 'id-go', jumlah: 0 }],
  ['8', { kode: 'id-ja', jumlah: 0 }],
  ['9', { kode: 'id-jr', jumlah: 0 }],
  ['10', { kode: 'id-jt', jumlah: 0 }],
  ['11', { kode: 'id-ji', jumlah: 0 }],
  ['12', { kode: 'id-kb', jumlah: 0 }],
  ['13', { kode: 'id-ks', jumlah: 0 }],
  ['14', { kode: 'id-kt', jumlah: 0 }],
  ['15', { kode: 'id-ki', jumlah: 0 }],
  ['16', { kode: 'id-ku', jumlah: 0 }],
  ['17', { kode: 'id-kr', jumlah: 0 }],
  ['18', { kode: 'id-1024', jumlah: 0 }],
  ['19', { kode: 'id-ma', jumlah: 0 }],
  ['20', { kode: 'id-la', jumlah: 0 }],
  ['21', { kode: 'id-ac', jumlah: 0 }],
  ['22', { kode: 'id-nb', jumlah: 0 }],
  ['23', { kode: 'id-nt', jumlah: 0 }],
  ['24', { kode: 'id-pa', jumlah: 0 }],
  ['25', { kode: 'id-ib', jumlah: 0 }],
  ['26', { kode: 'id-ri', jumlah: 0 }],
  ['27', { kode: 'id-sr', jumlah: 0 }],
  ['28', { kode: 'id-se', jumlah: 0 }],
  ['29', { kode: 'id-st', jumlah: 0 }],
  ['30', { kode: 'id-sg', jumlah: 0 }],
  ['31', { kode: 'id-sw', jumlah: 0 }],
  ['32', { kode: 'id-sb', jumlah: 0 }],
  ['33', { kode: 'id-sl', jumlah: 0 }],
  ['34', { kode: 'id-su', jumlah: 0 }],
])

console.log(Array.from(provinsi))
